language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.31.0
sudo: false
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo build --features "serde" --verbose
  - cargo test --verbose
