[package]
name = "keyboard-types"
version = "0.1.0"
authors = ["Pyfisch <pyfisch@gmail.com>"]
description = "Contains types to define keyboard related events."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/pyfisch/keyboard-types"
documentation = "https://docs.rs/crate/keyboard-types"
keywords = ["keyboard", "input", "event"]

[dependencies]
bitflags = "0.9.1"
serde = { version = "1.0.0", optional = true, features = ["derive"] }

[badges]
travis-ci = { repository = "https://github.com/pyfisch/keyboard-types" }